/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.bean.AtributoCadastrarCliente;
import model.dao.CadCliente;

/**
 *
 * @author gustavo rivolli
 */
public class formCadastrarCliente extends javax.swing.JFrame {
  

    /**
     * Creates new form formCadastrarCliente
     */
    public formCadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtFonePrincipal = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFoneRecado = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        cbOrigem = new javax.swing.JComboBox<>();
        cbSexo = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txfData = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txfCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 109, 500, -1));
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 161, 252, -1));

        txtFonePrincipal.setBounds(30, 200, 200, 30);
        getContentPane().add(txtFonePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 208, 252, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, 500, -1));
        getContentPane().add(txtFoneRecado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 208, 172, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 74, 114, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 208, 127, -1));
        getContentPane().add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 161, 127, -1));

        cbOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido", "Facebook", "Amigo", "Radio", "Panfleto", "Televisao" }));
        getContentPane().add(cbOrigem, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 252, 172, -1));

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "M", "F", " " }));
        getContentPane().add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 161, 172, -1));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 377, 565, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 429, 448, -1));

        txtNumero.setMinimumSize(new java.awt.Dimension(6, 30));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 377, 148, -1));
        getContentPane().add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 429, 184, -1));
        getContentPane().add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 532, 800, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 480, 665, -1));

        cbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbUf.setSelectedIndex(20);
        getContentPane().add(cbUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 480, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 612, -1, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 612, -1, -1));

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 77, -1, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 112, -1, -1));

        jLabel3.setText("CPF ou CNPJ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 164, -1, -1));

        jLabel4.setText("Fone Principal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 211, -1, -1));

        jLabel5.setText("E-Mail:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 255, -1, -1));

        jLabel6.setText("RG ou IE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 164, -1, -1));

        jLabel7.setText("Celular:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 211, -1, -1));

        jLabel8.setText("Data Nasc.:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 112, -1, -1));

        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 164, -1, -1));

        jLabel10.setText("Fone Recado:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 211, -1, -1));

        jLabel11.setText("Origem:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 255, -1, -1));

        jLabel12.setText("CEP:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 336, -1, -1));

        jLabel13.setText("Endereço:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 380, -1, -1));

        jLabel14.setText("Bairro:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 432, -1, -1));

        jLabel15.setText("Cidade:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 483, -1, -1));

        jLabel16.setText("Referencia:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 535, -1, -1));

        jLabel17.setText("Numero:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 380, -1, -1));

        jLabel18.setText("Complemento:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 432, -1, -1));

        jLabel19.setText("UF:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 483, -1, -1));

        try {
            txfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 109, 172, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 305, 930, 12));

        try {
            txfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 333, 126, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        AtributoCadastrarCliente acc = new AtributoCadastrarCliente();
        CadCliente cadCliente = new CadCliente();
            acc.setCodigo(txtCodigo.getText());
            acc.setNome(txtNome.getText());
            acc.setDataNasc(txfData.getText());
            acc.setCpf(txtCpf.getText());
            acc.setRg(txtRg.getText());
            acc.setSexo(String.valueOf(cbSexo.getSelectedIndex())) ;
            acc.setFonePrincipal(txtFonePrincipal.getText()) ;
            acc.setCelular(txtCelular.getText()) ;
            acc.setFoneRecado(txtFoneRecado.getText()) ;
            acc.setEmail(txtEmail.getText()) ;
            acc.setOrigem(String.valueOf(cbOrigem.getSelectedIndex())) ;
            acc.setCep(txfCep.getText()) ;
            acc.setEndereco(txtEndereco.getText()) ;
            acc.setNumero(txtNumero.getText()) ;
            acc.setBairro(txtBairro.getText()) ;
            acc.setComplemento(txtComplemento.getText()) ;
            acc.setCidade(txtCidade.getText()) ;
            acc.setUf(String.valueOf(cbUf.getSelectedIndex())) ;
            acc.setReferencia(txtReferencia.getText()) ;
            cadCliente.cadCliente(acc);
            

            txtCodigo.setText("");
            txtNome.setText("");
            txfData.setText("");
            txtCpf.setText("");
            txtRg.setText("");
            cbSexo.setSelectedIndex(0);
            txtFonePrincipal.setText("");
            txtCelular.setText("");
            txtFoneRecado.setText("");
            txtEmail.setText("");
            cbOrigem.setSelectedIndex(0);
            txfCep.setText("");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            txtComplemento.setText("");
            txtCidade.setText("");
            cbUf.setSelectedIndex(20);
            txtReferencia.setText("");
            
            
           





    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbOrigem;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField txfCep;
    private javax.swing.JFormattedTextField txfData;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFonePrincipal;
    private javax.swing.JTextField txtFoneRecado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtRg;
    // End of variables declaration//GEN-END:variables




 public void carregarCliente(String codigo){
     CadCliente cadCliente = new CadCliente();   
     ArrayList<AtributoCadastrarCliente> cliente= new ArrayList<>();
     cliente = cadCliente.buscarCliete(codigo);
     
     
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
     SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyy");
     Date data = null;   
     try {
            data =sdf.parse(cliente.get(0).getDataNasc());
        } catch (ParseException ex) {
            Logger.getLogger(formCadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     txtCodigo.setText(cliente.get(0).getCodigo());
     txtNome.setText(cliente.get(0).getNome());
     txfData.setText(sdf2.format(data));
     txtCpf.setText(cliente.get(0).getCpf());
     txtRg.setText(cliente.get(0).getRg());
     cbSexo.setSelectedIndex(Integer.parseInt(cliente.get(0).getSexo()));
     txtFonePrincipal.setText(cliente.get(0).getFonePrincipal());
     txtCelular.setText(cliente.get(0).getCelular());
     txtFoneRecado.setText(cliente.get(0).getFoneRecado());
     txtEmail.setText(cliente.get(0).getEmail());
     cbOrigem.setSelectedIndex(Integer.parseInt(cliente.get(0).getOrigem()));
     txfCep.setText(cliente.get(0).getCep());
     txtEndereco.setText(cliente.get(0).getEndereco());
     txtNumero.setText(cliente.get(0).getNumero());
     txtBairro.setText(cliente.get(0).getBairro());
     txtComplemento.setText(cliente.get(0).getComplemento());
     txtCidade.setText(cliente.get(0).getCidade());
     cbUf.setSelectedIndex(Integer.parseInt(cliente.get(0).getUf()));
     txtReferencia.setText(cliente.get(0).getReferencia());
   

 }




}
